apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: specific-child-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/hvl71/redis-helm.git
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: specific-child-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

